[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@chainlink/contracts/=node_modules/@chainlink/contracts/']

[rpc_endpoints]
mainnet = "wss://mainnet.infura.io/ws/v3/074e6045535d48209742de982d6dad5a"
sepolia = "wss://sepolia.infura.io/ws/v3/074e6045535d48209742de982d6dad5a"