[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.24"
evm_version = "cancun"

[rpc_endpoints]
mainnet = "wss://mainnet.infura.io/ws/v3/074e6045535d48209742de982d6dad5a"
sepolia = "wss://sepolia.infura.io/ws/v3/074e6045535d48209742de982d6dad5a"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config